### ISSUE TITLE
Can't restore my crypto-assets

### ISSUE THREAD

**Issue by mbalance** [oed/seedsplit#12]
Hello again :)

I'm combining the shards I created but the key that I'm getting is showing the wrong addresses, with zero balance, when I import it into Mycrypto App or Electrum Bitcoin wallet.

I have tried both the compiled version cli-win and cli-linux and the npm installer on ubuntu with bip39 2.3.0. They all give me the same output which seems to be different from what I split back in 2017.

**Comment by mbalance** [comment]
Oh, I forgot to mention, it was a 24 word Ledger Nano S seed.

**Comment by mbalance** [comment]
Alright figured it out.

Had to specify the section to `m/44'/60'/0'`

**Comment by oed** [comment]
Glad you figured it out! :D
